import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Components
import NavBar from "@/components/Nav/NavBar/NavBar";

// Redux
import { AuthProvider } from "@/components/AuthProvider";

const poppis = Poppins({
  subsets: ["latin"],
  weight: ["400","600"]
}, )

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={poppis.className}>
        <AuthProvider>
          <NavBar />
          {children}
        </AuthProvider>
        </body>
    </html>
  );
}
