import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// components
import NavBar from "@/components/Nav/NavBar";

const poppis = Poppins({
  subsets: ["latin"],
  weight: ["400","600"]
}, )

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={poppis.className}>
        <NavBar />
        {children}
        </body>
    </html>
  );
}
