"""remove restaurant_dish relationship

Revision ID: 05ed11d689eb
Revises: c1d9c03668b9
Create Date: 2025-11-05 20:25:26.029174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ed11d689eb'
down_revision: Union[str, Sequence[str], None] = 'c1d9c03668b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
