"""Category column added

Revision ID: 6c67aa251e71
Revises: bfdcad3165ad
Create Date: 2025-11-04 18:54:12.681931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c67aa251e71'
down_revision: Union[str, Sequence[str], None] = 'bfdcad3165ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('dishes_restaurant_id_fkey'), 'dishes', type_='foreignkey')
    op.drop_column('dishes', 'restaurant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('dishes_restaurant_id_fkey'), 'dishes', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###
