"""Category column added

Revision ID: b1f6cfce312e
Revises: b60193b86ffb
Create Date: 2025-11-04 18:20:34.346362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f6cfce312e'
down_revision: Union[str, Sequence[str], None] = 'b60193b86ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinks', sa.Column('category_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('drinks_restaurant_id_fkey'), 'drinks', type_='foreignkey')
    op.drop_column('drinks', 'restaurant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinks', sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('drinks_restaurant_id_fkey'), 'drinks', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_column('drinks', 'category_id')
    # ### end Alembic commands ###
