"""Category column added

Revision ID: eb3c1005f33e
Revises: b1f6cfce312e
Create Date: 2025-11-04 18:23:28.897046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3c1005f33e'
down_revision: Union[str, Sequence[str], None] = 'b1f6cfce312e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dishes', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dishes', type_='foreignkey')
    op.drop_column('dishes', 'restaurant_id')
    # ### end Alembic commands ###
